sudo: required
services:
  - docker
language: csharp
script:
  # Build the builder image
  - docker build -t build-image -f Dockerfile.build .
  # Create a container from the built image
  - docker create --name build-cont build-image
  # Copy binaries
  - docker cp build-cont:/out ./PublishOutput
  # Build the productin image
  - docker build -t ba2017/webshop-poc:0.1 -f Dockerfile.prod .
  # Login to docker hub
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  # Push docker image
  - docker push ba2017/webshop-poc:0.1