FROM microsoft/aspnetcore-build

ARG CLRDBG_VERSION=VS2015U2
WORKDIR /clrdbg
RUN apt-get update && apt-get install -y \
    unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -SL https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh --output GetClrDbg.sh \
    && chmod 700 GetClrDbg.sh \
    && ./GetClrDbg.sh $CLRDBG_VERSION \
    && rm GetClrDbg.sh

WORKDIR /app

COPY *.csproj .
RUN dotnet restore

ENV ASPNETCORE_URLS http://*:9000
ENV ASPNETCORE_ENVIRONMENT Development
ENV REMOTE_DEBUGGING

ENTRYPOINT dotnet watch run
